# Generated by Django 3.2.5 on 2021-08-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_status',
            new_name='register_students',
        ),
    ]
