# Generated by Django 3.2.5 on 2021-08-08 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_rename_register_status_register_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_students',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
