# Generated by Django 3.2.5 on 2021-08-08 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_alter_register_students_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_students',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
