# Generated by Django 3.2.5 on 2021-08-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_register_students_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_students',
            name='birthdate',
        ),
    ]
