# Generated by Django 3.2.5 on 2021-08-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_remove_register_students_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_students',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
